### ISSUE TITLE
clean variable in circulars index causing issues with displaying results

### ISSUE THREAD

**Issue by tylerbarna** [nasa-gcn/gcn.nasa.gov#1110]
The use of the clean constant in index.tsx for the circulars page is causing an issue with other form elements that are being added which causes the results to not be displayed. This is because clean is evaluated as false in cases where it should be evaluating as true. Manually setting clean to be true resolves the issue, but I'm unsure how to modify the current implementation of the clean constant to both preserve the intent of the clean constant and also prevent this issue

This behaviour can be replicated in the current public site by searching a query, submitting it, and, after loading, clicking on the circulars navigation link. The results will no longer appear, though the search form will still be populated (there will be no url parameter string, and printing it to console will show it's not defined, so it should just display the full results list). I don't believe the search form being populated is the underlying issue but rather the clean constant being evaluated as false, as mentioned above.

It can also be replicated by running PR #1104 locally and changing the number of results to display with or without submitting a query, though the results will load correctly if one refreshes the browser page without altering the url query parameters

**Comment by nulfrost** [comment]
Hey there 👋🏿 may I take a stab at this? So I believe I understand what's going on.

- Before you start typing in anything, inputQuery and query are undefined so the 'clean' variable will be true
- When you start typing in the search input, inputQuery is no longer undefined and is a string. string != undefined so clean is false. This is why the search results disappear as well.
- Hitting enter submits the form and so now inputQuery and query are true since they now have the same value.
- Clicking the circulars link in the navbar clears the query since you're navigating away from "?query=thing" to "/circulars", so now query is undefined and "clean" will evaluate to false. So no search results.

A few questions about the desired UX.

1. Does the query need to be updated on every keystroke? Or is just submitting the form after the user hits enter or clicks the search icon fine? I feel like the latter would be better UX
2. Should the text in the input be retained or be cleared whenever someone searches for something after the initial search?
3. Similar question for the limit search param, should that be retained in the URL when someone does a new search?
