### ISSUE TITLE
Kafka Instances become unresponsive

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2442]
# Current behavior
Kafka instances don't allow login and users see error "Network is unreachable"

# Expected behavior
Stability

# Steps to reproduce

# Environment

**Comment by dakota002** [comment]
It is likely that our configuration may not be quite right after our latest updates to the infrastructure. I am not 100% at the moment, but i think we should review what we are running the brokers and everything on and make sure we are staying consistent with the specs. 

This white paper  has a Capacity Planning section (page 10) that may be helpful
https://www.confluent.io/wp-content/uploads/apache-kafka-confluent-enterprise-ref-architecture.pdf

**Comment by lpsinger** [comment]
Confluent's resource suggestions are overkill for us.

I determined that the cause of the outages. I consulted the instance logs around the time of one of the outages and I found that the root volume was full. I logged in to some of the remaining instances that were still up. I found that disk space occupied by the directory /var/log/kafka was very large on some instances, and that older instances had much larger /var/log/kafka directories. I deduced that the daily rolling log files (for example, /var/log/kafka/server.log.2024-07-20-21) are never deleted.

The [API documentation for DailyRollingFileAppender](https://logging.apache.org/log4j/1.x/apidocs/org/apache/log4j/DailyRollingFileAppender.html) makes it clear that this is so. Also, according to the [Confluent platform documentation](https://docs.confluent.io/platform/current/monitor/cp-logging.html#appender-types):

> org.apache.log4j.DailyRollingFileAppender - This is the default file appender for Kafka. It provides regular time-based files. Note that this log appender does not clean up files automatically and requires manual intervention to remove old log files.

https://github.com/nasa-gcn/gcn-infrastructure/pull/4 will fix the outages by adding a daily systemd timer to delete old log files. No telemetry will be lost because the log files are replicated to CloudWatch.
