### ISSUE TITLE
Circulars link not clickable

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2563]
# Current behavior

Some links automatically generated by astro flavored markdown to other GCN Circulars don't let you click on them, but you can open them in another tab.

# Expected behavior

All links should work the same.

# Steps to reproduce

GCN 37373

# Environment

Safari

**Comment by tylerbarna** [comment]
From console on broken links: "﻿﻿Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received"

**Comment by tylerbarna** [comment]
## Reproducible error
In [GCN 37292](https://gcn.nasa.gov/circulars/37292) (submitted via web form), there are several different Circulars referenced that may point towards what the issue could be:
- In the second paragraph, Circulars [37274](https://gcn.nasa.gov/circulars/37274) and [37273](https://gcn.nasa.gov/circulars/37273) are both referenced, and these hyperlinks correctly load the page. These two circulars were submitted via email.
- In the third paragraph, there are 8 separate Circulars that are referenced, with all of these links failing to load. All of these Circulars were submitted via the web form
- When clicking any Circular hyperlink that doesn't load properly, the URL is updated to match the Circular that fails to load
- If a user clicks on several broken hyperlinks before clicking on a functional hyperlink, navigating to the previous page using the browser back button (*not* the in-page navigation) will load the Circulars with broken links that were clicked on rather than the original Circular
- If a user clicks on several broken hyperlinks and attempts to use the in-browser back button, the URL updates to reflect the Circular IDs of the broken hyperlinks without the page re-rendering the page from the original Circular. Manually reloading the page while the URL contains one of the broken Circular IDs does render that Circular, however.

## Takeaways
- There may be some relation between the hyperlinks working and whether or not they were submitted via the web form, with those submitted via webform not loading
- Clicking on broken hyperlinks updates the URL without reloading the page to reflect the different Circular. These updated URLs are included in the history of the browser after navigating with a functional hyperlink.

**Comment by lpsinger** [comment]
This broke in the update from Remix v2.10.3 to v2.11.0.

**Comment by lpsinger** [comment]
[`git bisect`](https://git-scm.com/docs/git-bisect) suggests that one of the following commits broke this:

- https://github.com/remix-run/remix/commit/08731d944a3785f5541bc38ef4493c8939103e53
- https://github.com/remix-run/remix/commit/ef612a729bf6acd6b9a11ba6c3971beb1f1760f1
- https://github.com/remix-run/remix/commit/b163e06f66ae3d238fe633889d08bef823868d27
- https://github.com/remix-run/remix/commit/c00e3652a1e5209796b1f84b195869eb7d20ecf6
- https://github.com/remix-run/remix/commit/e171af77fe8ed12c91674c9e9f8d779f758cd2eb
- https://github.com/remix-run/remix/commit/5a9bcd53977dfbded74c1b1b468c32cc5a12ec7c
- https://github.com/remix-run/remix/commit/cfc0c6f14f6934bf9806ea0cd96e61dd51c2e784
- https://github.com/remix-run/remix/commit/2c8eecd3788f38ad13c65cdb31fa4e29f16fb33a
