### ISSUE TITLE
issue templates are no longer options

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2658]
### Description
After we merged in the New Producer issue template (PR #2627) specifically into the gcn.nasa.gov repo, the organization-wide issue templates for enhancements and bug reports are no longer available as templates when opening a ticket on the nasa-gcn project board or in the issues page.

### Acceptance Criteria
All of the issue template options previous generated should be listed as options when opening a new issue.

**Comment by dakota002** [comment]
I'm pretty sure it is happening because the new issue template is defined in this project, so it overwrites whatever would be defined at the org level, which is where the others are defined. The org defined ones are a fall back case.

So I think https://github.com/nasa-gcn/.github/pull/19 was the correct way to implement this if we want all of the issue templates on this project

@lpsinger, @jracusin Should we just reopen that PR and remove the template from this repo?

**Comment by lpsinger** [comment]
According to https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#about-default-community-health-files:

> If a repository has any files in its own .github/ISSUE_TEMPLATE folder, including issue templates or a config.yml file, none of the contents of the default .github/ISSUE_TEMPLATE folder will be used.

**Comment by lpsinger** [comment]
Let's go with the former, so there is less risk of copy-and-paste errors.
