### ISSUE TITLE
Write a toy remark plugin

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#303]
Write a toy [remark plugin](https://github.com/remarkjs/remark/blob/HEAD/doc/plugins.md) to prototype the concept for Astro Flavored Markdown (#302). Suggestion: write a plugin that recognizes and parses ISO 8601 formatted times and outputs a special AST node.

Definition of done: a standalone repo containing a Node.js project that implements the plugin, plus example code, example input, and example AST output.

**Comment by dakota002** [comment]
I started this one, [Astro-Flavored-Markdown](https://github.com/nasa-gcn/Astro-Flavored-Markdown), just as a starting point

**Comment by lpsinger** [comment]
Oh, neat! Does it work?

**Comment by dakota002** [comment]
Kinda! I'm still learning a bit about the design patterns that other similar packages follow, but it seems to work in my local tests. I made a branch on my gcn fork, and added the local version of the plugin. Finding and replacing the value of the ISO 8601 time seems to work, but the replaced value (the original value wrapped with strong tags) is being rendered as a string, instead of html


![image](https://user-images.githubusercontent.com/11023698/209985705-fc973ebf-9c90-44c8-a207-86ee63da390f.png)

**Comment by lpsinger** [comment]
OK. Note that we'll want the plugin to emit AST nodes rather than non-semantic HTML. The division of labor should be (if I understand it correctly):

- Plugin emits AST nodes
- Web site remix.config.js transforms AST nodes to HTML

What if we made a standalone demo editor to test this out? Three side by side panes: Markdown input, AST output, rendered HTML?

**Comment by lpsinger** [comment]
It's fair to say that https://github.com/nasa-gcn/remark-rehype-astro is much more than a "toy" plugin, so I'm closing this!
