### ISSUE TITLE
Add dev banner to emails

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#790]
Email notifications from the dev and test environments should be clearly distinguished from production. Add something similar to the web site's development banner to all emails.

**Comment by dakota002** [comment]
@lpsinger we are currently using the Text body. Should we switch to use HTML email bodies? 

If we want to just stick with the plain text responses, does something like this work:
![image](https://user-images.githubusercontent.com/11023698/233714591-fff9673d-bf59-4f65-97a7-2b4c26416073.png)

Otherwise, if we switch to html we can style it up a bit, like this rough one: (Literally copied the html from the site, I think the pink ish color is from outlook trying to do some dark mode stuff, that should be the same color as the dev banner, #9c3610)
![image](https://user-images.githubusercontent.com/11023698/233715335-d5b48311-ca83-41c2-9a37-e03feafe02e5.png)

**Comment by lpsinger** [comment]
I do like the styled version, but sadly many longtime users doubtless rely on these messages being plain text. So let's go with the earlier version.

Also, rather than "You are viewing..." perhaps "This notification is from..."
