### ISSUE TITLE
Write policy on corrections to Circulars

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#869]
Decide on and document a policy for corrections to Circulars, possibly with input from the community. Definition of Done: a new docs page under /docs/circulars.

- [ ] How do we treat duplicate or mistaken submissions? Do we delete them outright, or do we mark them up with GCN OP NOTE or editorial remarks? What notation do we use?
- [ ] For what kinds of changes are we willing to make editorial corrections? For what kinds of changes should users submit new Circulars?
- [ ] How should users note that a Circular is an erratum or correction to an earlier Circular?

**Comment by jracusin** [comment]
Utilizing @dakota002 new feature for circular moderation:

> How do we treat duplicate or mistaken submissions? Do we delete them outright, or do we mark them up with GCN OP NOTE or editorial remarks? What notation do we use?

We will keep them in the web archive (separate table not indexed in search), but add a Version 2 with subject replaced with "Duplicate Submission" or "Mistaken Submission" and the body will be something like "This Circular was removed from the archive due to an erroneous submission".  If duplicate, could point to original.

> For what kinds of changes are we willing to make editorial corrections? For what kinds of changes should users submit new Circulars?

We are only willing to make erratum corrections (author lists, misspellings, typos, event name, correcting data that doesn't have substantive impact on follow up).  Users should submit new circulars when they have updates to their observations or analysis.  In the retractions or changed to source name, the moderator will have option to "save and distribute".

> How should users note that a Circular is an erratum or correction to an earlier Circular?

Versions will be displayed on every circular page with a history.  Prior versions are always visible, similar to arXiv.
