### ISSUE TITLE
GCN circular submission thorugh circulars@gcn.nasa.gov was not distributed

### ISSUE THREAD

**Issue by JoeMangan** [nasa-gcn/gcn.nasa.gov#871]
Hello, I had an issue submitting a GCN using the circulars@gcn.nasa.gov email address. I didn't get an acknowledgement email response and the GCN didn't seem to be distributed. I used the online form on the new GCN site in the end to post the GCN.

**Comment by lpsinger** [comment]
Hi Joe. I see your email submission. Our system rejected it because it did not pass SPF, DKIM, or DMARC checks. SPF, DKIM, and DMARC are anti-spam technologies that provide some protection against forgery --- they help us to make sure that when we get an email from you, that it really did come from you.

Currently, we require at least one of SPF, DKIM, or DMARC to pass, but in this case all three failed. SPF, DKIM, and DMARC all rely on your institution defining certain entries in DNS. Would you please contact your institution (IJCLab, I gather) and ask them to check if they have SPF, DKIM, and DMARC configured correctly for their mail servers?

**Comment by lpsinger** [comment]
We've disabled the SPF, DKIM, and DMARC checks.
